### ISSUE TITLE
When will you release your code?

### ISSUE THREAD

**Issue by sadsadsafsefadfa** [swyoon/aaai2021-scene-graph-img-retr#1]
Hello,

I am very interested in how you implemented your paper on Image-to-Image Retrieval by Learning Similarity between Scene Graphs. I hope that you can release your code, soon.

Thanks

**Comment by swyoon** [comment]
Dear @sadsadsafsefadfa

I am terribly sorry for the late release.

I have released our human experiment data along with the ids of visual genome images and a code for computing inter-human agreement.

I will also release prediction results from our models and baselines shortly.

Thank you for your attention to our work.

Best,
Sangwoong Yoon.
